<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Gautham-Laptop" failures="1" tests="2" name="test6" time="0.05" errors="0" timestamp="2021-03-19T20:44:35 IST">
  <testcase classname="TechM.TestNG.TestNG4" name="failTC1" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TechM.TestNG.TestNG4.failTC1(TestNG4.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- failTC1 -->
  <testcase classname="TechM.TestNG.TestNG4" name="failTC2" time="0.001"/>
  <testcase classname="TechM.TestNG.TestNG4" name="passTC1" time="0.0">
    <ignored/>
  </testcase> <!-- passTC1 -->
  <testcase classname="TechM.TestNG.TestNG4" name="passTC2" time="0.0">
    <ignored/>
  </testcase> <!-- passTC2 -->
  <testcase classname="TechM.TestNG.TestNG4" name="runFinal" time="0.0">
    <ignored/>
  </testcase> <!-- runFinal -->
</testsuite> <!-- test6 -->
